const { agentsDB, logsDB, integrationsDB } = require('../models/database');

/**
 * Nexus AI Agent Execution Engine
 * Natively executes real-world actions for autonomous nodes.
 */

async function runAgent(agent) {
  const userId = agent.userId;
  const userIntegrations = integrationsDB[userId];
  // Secure fallback to system-level token if user-specific token is uninitialized
  const githubToken = userIntegrations?.github?.accessToken || process.env.GITHUB_ACCESS_TOKEN;

  if (!githubToken) {
    console.error(`[Agent Engine] No GitHub token mapped for user ${userId}. Skipping unit ${agent.id}.`);
    return;
  }

  try {
    const { repo, issueTitle, issueBody } = agent.config || {};
    let actionResult = null;
    let logMessage = '';

    if (agent.type === 'github-monitor') {
      // Fetch latest commits
      const response = await fetch(`https://api.github.com/repos/${repo}/commits?per_page=5`, {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'User-Agent': 'NexusAI-Agent'
        }
      });
      
      if (!response.ok) throw new Error(`GitHub API Error: ${response.status} ${response.statusText}`);
      
      const commits = await response.json();
      actionResult = { count: commits.length, latest: commits[0]?.commit?.message };
      logMessage = `Synced ${commits.length} latest commits from ${repo}. Latest: "${commits[0]?.commit?.message.substring(0, 30)}..."`;
    } 
    
    else if (agent.type === 'issue-creator') {
      // Create a GitHub issue
      const response = await fetch(`https://api.github.com/repos/${repo}/issues`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
          'User-Agent': 'NexusAI-Agent'
        },
        body: JSON.stringify({
          title: issueTitle || `Autonomous Issue - ${new Date().toLocaleTimeString()}`,
          body: issueBody || 'This issue was automatically generated by a Nexus AI Autonomous Agent.'
        })
      });

      if (!response.ok) throw new Error(`GitHub API Error: ${response.status} ${response.statusText}`);
      
      const issue = await response.json();
      actionResult = { id: issue.id, url: issue.html_url };
      logMessage = `Successfully created GitHub issue: "${issue.title}" in ${repo}.`;
    }

    // Capture execution telemetry
    logsDB.push({
      id: 'log_' + Math.random().toString(36).substr(2, 9),
      agentId: agent.id,
      userId: agent.userId,
      timestamp: new Date().toISOString(),
      action: agent.type,
      result: logMessage,
      data: actionResult
    });

    console.log(`[Agent Engine] Unit ${agent.id} execution successful: ${logMessage}`);

  } catch (error) {
    console.error(`[Agent Engine] Unit ${agent.id} terminal failure:`, error.message);
    logsDB.push({
      id: 'log_' + Math.random().toString(36).substr(2, 9),
      agentId: agent.id,
      userId: agent.userId,
      timestamp: new Date().toISOString(),
      action: agent.type,
      result: `Execution failed: ${error.message}`,
      type: 'ERROR'
    });
  }
}

/**
 * Autonomous Loop System
 * Orchestrates the heartbeats of all active nodes.
 */
function startAgentLoop() {
  console.log('[Agent Engine] Initializing Nexus Autonomy Loop (Interval: 15s)...');
  
  setInterval(async () => {
    const activeAgents = agentsDB.filter(a => a.status === 'Active');
    
    if (activeAgents.length === 0) return;
    
    console.log(`[Agent Engine] Processing ${activeAgents.length} active autonomous units...`);
    
    for (const agent of activeAgents) {
      await runAgent(agent);
    }
  }, 15000); // 15-second core cycle
}

module.exports = { startAgentLoop };
